### PR TITLE
styledMapType and updateInterval

### PR DESCRIPTION
**Pull request by ogelinas**
styledMapType : Allow user to change the color of the map
updateInterval: Allow user to specify when reload the map

### CODE REVIEW

**Comment by E3V3A** [comment]
@vicmora 
Any reason you don't want to merge this?

**Comment by GeekyTiki** [comment]
@ogelinas Hey, do I just download all of these and replace vicmora's respective files in the module folder? I'm trying to change the default map to the night/dark style one.

**Comment by ogelinas** [comment]
@GeekyTiki, I am not a big user of Github. It could work if you replace the files like you mentioned. But if @vicmora push the change, you will have more step to resync the update. Alternatively, you can remove all vicmora's addon and install it direclty from my repo. [https://github.com/ogelinas/MMM-GoogleMapsTraffic](url). Personnally, I would prefer to not fork the project and keep this repo, active. Otherwise, its look like someone have fork my repo : [https://github.com/scheckmedia/MMM-GoogleMapsTraffic](url).

**Comment by vicmora** [comment]
sorry for the delay, merged

**Pull request merged**
